name = "clortho"
description = "Shiny new project"
version = "0.0.0"

authors = ["Riccardo Bernardini"]
maintainers = ["Riccardo Bernardini <riccardo.bernardini@uniud.it>"]
maintainers-logins = ["mockturtle"]

executables = ["clortho"]
[[depends-on]]  # Added by alr
sparknacl = "^2.0.0"  # Added by alr
[[depends-on]]  # Added by alr
uri_ada = "^1.0.0"  # Added by alr
[[depends-on]]  # Added by alr
get_password = "^1.0.0-rc"  # Added by alr
